[default]
SLACK_WEB_HOOK_URL = "https://hooks.slack.com/services/YOUR_WEBHOOK_URL"
DEBUG = "INFO"
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AWS_DEFAULT_REGION="ca-central-1"
AWS_BUCKET=""

[production]
# ...Bucket

[local]
# ...
