[project]
name = "template_python"
version = "1.0.0"
description = "Python default configuration"
authors = ["K1 <keven.voyer.1@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.11.4.*"
ruff = "0.0.286.*"
pre-commit = "3.3.3.*"
rich = "13.5.1.*"
dynaconf = "3.2.0.*"
ipykernel = "6.25.1.*"
