name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  Quality:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.3.1-0'
          environment-file: pixi.lock
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'

      - name: Import numpy in micromamba environment (bash)
        run: python -c "import numpy"
        shell: bash -el {0}

      - name: Run custom command in micromamba environment
        run: pytest --version
        shell: micromamba-shell {0}

      - name: Run Pre-Commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --hook-stage push

    #   - name: Run Pytest
    #     run: poetry run pytest
