name: ci
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
jobs:
  Quality:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
        with:
          submodules: true
          
      - name: Install Python
        id: setup-python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.11"
          
      - name: Rename Lock File
        run: mv pixi.lock conda-lock.yml
        shell: bash
        
      - name: setup-micromamba
        # You may pin to the exact commit or the version.
        # uses: mamba-org/setup-micromamba@875557da4ee020f18df03b8910a42203fbf02da1
        uses: mamba-org/setup-micromamba@v1.4.3
        with:
          environment-name: ml
          environment-file: conda-lock.yml
          init-shell: bash
          # Which kind of cleanup to do after the action.
          # `'none'` - do not cleanup anything.
          # `'shell-init'` - cleanup only the shell initialization scripts.
          # `'environment'` - cleanup the installed environment and shell initialization scripts.
          # `'all'` - cleanup everything including the whole micromamba root folder and the micromamba binary.
          post-cleanup: 'all'
          

      - name: Import numpy in micromamba environment (bash)
        run: python -c "import pandas"
        shell: bash -el {0}

      - name: Run custom command in micromamba environment
        run: pytest --version
        shell: micromamba-shell {0}

      - name: Run Pre-Commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files --hook-stage push

    #   - name: Run Pytest
    #     run: poetry run pytest
